### ISSUE TITLE
Cockpit exists check fails when running automatic testing locally without portal running

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/ays_automatic_cockpit_based_testing#52]
https://github.com/Jumpscale/ays_automatic_cockpit_based_testing/blob/2cfa8511a7699f015f56dd638eb3830720ea0260/cockpit_testing/Framework/utils/utils.py#L359 

Checking for cockpit existence is done via checking the response of the portal (host:80) which isn't always the case.

**Comment by islamTaha12** [comment]
The driver is designed to be compatible with Installer. 
If u need to skip checking portal, comment this line
https://github.com/Jumpscale/ays_automatic_cockpit_based_testing/blob/master/cockpit_testing/Framework/Driver/Driver.py#L23
