### ISSUE TITLE
fix test add_user_to_vm.yaml

### ISSUE THREAD

**Issue by ramezsaeed** [Jumpscale/ays_automatic_cockpit_based_testing#54]
https://github.com/Jumpscale/ays_jumpscale8/blob/8.1.1/tests/bp_test_templates/basic/add_user_to_vm.yaml

`jenkins@du-conv-2-jenkins:~/workspace/ays_automatic_cockpit_based_testing$ python3 cockpit_testing/Framework/Driver/Driver.py -b add_user_to_vm.yaml
 * Driver is running ..... 
 * Create new account .... 
 * Test case : add_user_to_vm.yaml
 * CREATED : a355ed1023 repo
 * CREATED : 8062ae8a31 blueprint in a355ed1023 repo
 * ERROR : response status code 403 response content b'{\n  "error": "Error during execution of the blueprint:\\n ERROR: The arguments passed to the service contains the following errors: \\n- Invalid parameter [uservdc] passed while creating test_add_user_to_vm!c9a47abbe5.\\n\\n- Invalid parameter [node] passed while creating test_add_user_to_vm!c9a47abbe5.\\n\\n- Invalid parameter [g8client] passed while creating test_add_user_to_vm!c9a47abbe5.\\n\\nDataSchema : \\n@0xa69ffab47e0e5441;\\nstruct Schema {\\n\\n}\\n ((type:input.error)"\n}\n' 
 * Generate XML results`

**Comment by islamTaha12** [comment]
Fixed.
Renamed schema.yml to schema.hrd
