### ISSUE TITLE
fix test network_configuration.yaml

### ISSUE THREAD

**Issue by ramezsaeed** [Jumpscale/ays_automatic_cockpit_based_testing#56]
`jenkins@du-conv-2-jenkins:~/workspace/ays_automatic_cockpit_based_testing$ python3 cockpit_testing/Framework/Driver/Driver.py -b network_configuration.yaml
 * Driver is running ..... 
 * Create new account .... 
 * Test case : network_configuration.yaml
 * CREATED : 77d4ca34ae repo
 * CREATED : b3d49142ef blueprint in 77d4ca34ae repo
 * ERROR : response status code 403 response content b'{\n  "error": "Error during execution of the blueprint:\\n ERROR: The arguments passed to the service contains the following errors: \\n- Invalid parameter [os] passed while creating test_network_configuration!ts1.\\n\\nDataSchema : \\n@0xb33855d25325ba8c;\\nstruct Schema {\\n\\tvdc @0 :Text;\\n\\timage @1 :Text;\\n\\tresult @2 :Text;\\n\\n}\\n ((type:input.error)"\n}\n' 
 * DELETED : 77d4ca34ae repo
 * Generate XML results
`

**Comment by islamTaha12** [comment]
miss os paramter in the schema 
vdc = type:string parent:vdc
os = type:string parent:os
image = type:string default:'Ubuntu 16.04 x64'
result = type:string
