### ISSUE TITLE
fix test create_account_cloudspace_with_specs.yaml

### ISSUE THREAD

**Issue by ramezsaeed** [Jumpscale/ays_automatic_cockpit_based_testing#58]
`jenkins@du-conv-2-jenkins:~/workspace/ays_automatic_cockpit_based_testing$ python3 cockpit_testing/Framework/Driver/Driver.py -b create_account_cloudspace_with_specs.yaml --teardown
 * Driver is running ..... 
 * Create new account .... 
 * Test case : create_account_cloudspace_with_specs.yaml
 * CREATED : 2f1fc0d516 repo
 * CREATED : 768686e7dc blueprint in 2f1fc0d516 repo
 * ERROR : response status code 500 response content b'{\n  "error": "Error during execution of the blueprint:\\n Cannot convert str to capnp.lib.capnp._DynamicListBuilder"\n}\n' 
 * DELETED : 2f1fc0d516 repo
 * Generate XML results
 * Execute teardown method .... 
jenkins@du-conv-2-jenkins:~/workspace/ays_automatic_cockpit_based_testing$ python3 cockpit_testing/Framework/Driver/Driver.py -b create_account_cloudspace_with_specs.yaml --teardown
 * Driver is running ..... 
 * Create new account .... 
 * Test case : create_account_cloudspace_with_specs.yaml
 * CREATED : c982770d5a repo
 * CREATED : 1943cc248c blueprint in c982770d5a repo
 * ERROR : response status code 500 response content b'{\n  "error": "Error during execution of the blueprint:\\n Cannot convert str to capnp.lib.capnp._DynamicListBuilder"\n}\n' 
 * DELETED : c982770d5a repo
 * Generate XML results
 * Execute teardown method .... `

**Comment by islamTaha12** [comment]
Fixed.
I modified the service schema to accept vdc list
vdc=type:str consume:vdc
g8client=type:str list consume:g8client
result=type:str
