### ISSUE TITLE
test_validate_delete_model_sample is not test case blueprint

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_automatic_cockpit_based_testing#62]
**Blueprint**
The test_validate_delete_model_sample blueprint isn't a test case but it is used in this service
https://github.com/Jumpscale/ays_jumpscale8/blob/8.1.1/tests/test_services/test_validate_delete_models/actions.py#L29
```xml 
<testcase classname="/cockpit_testing/Framework/TestCases/test_validate_delete_model_sample.yaml" name="test_validate_delete_model_sample.yaml" time="0">
  <error>
   service: Unknown service - Message: ERROR : Traceback (most recent call last):
  File "cockpit_testing/Framework/Driver/Driver.py", line 73, in work
    get_testService_role(blueprint=blueprint, thread_name=threading.current_thread().name)
  File "cockpit_testing/Framework/Driver/Driver.py", line 47, in get_testService_role
    raise NameError("The blueprint doesn't have any test roles.")
NameError: The blueprint doesn't have any test roles.
  </error>
```

**cockpit version**
8.1.1

**Comment by ahussein** [comment]
Yes. It was created in a different directory structure setup. This has the same root cause as

**Comment by ahussein** [comment]
https://github.com/Jumpscale/ays_automatic_cockpit_based_testing/issues/60

**Comment by islamTaha12** [comment]
I fixed it here
https://github.com/Jumpscale/ays_automatic_cockpit_based_testing/issues/62
